name: Release Staging

on:
  push:
    branches: [release/*]
  pull_request:
    branches: [release/*]

jobs:
  stage-release:
    runs-on: ubuntu-latest
    name: Stage Release Branch
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
             - name: Run tests
         run: bun test
        
      - name: Build project
        run: bun run build
        
      - name: Validate project structure
        run: bun run src/scripts/validate-structure.ts
        
      - name: Check configuration
        run: bun run src/scripts/check-config.ts
        
      - name: Stage deployment notification
        run: |
          echo "🚀 Release branch staged successfully!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Ready for final review and merge to main"
          
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 Release Branch Staged Successfully!
              
              **Branch:** \`${{ github.ref_name }}\`
              **Status:** ✅ All checks passed
              **Next Steps:**
              1. Final code review
              2. Merge to \`main\` branch
              3. Create GitHub release
              
              **Test Coverage:** ✅ Passed
              **Build:** ✅ Successful
              **Validation:** ✅ Passed`
            })
